### ISSUE TITLE
State timeline data

### ISSUE THREAD

**Issue by lucasrodes** [india-covid19vaccine/india-covid19vaccine.github.io#1]
Hi,
Thanks for your amazing work. The website, API and everything look really refined!

I would like to integrate your data into my data (https://github.com/sociepy/covid19-vaccination-subnational) and have a couple of questions:

- In the state timelines, (e.g. https://india-covid19vaccine.github.io/api/AR.json), the field `total` refers to all vaccinations or just the first dose? I presume that India currently is administering 1 dose, so total vaccinations = 1 dose at this stage.

**Comment by lucasrodes** [comment]
UPDATE: I will be using the [state_timeline.csv](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/csv/state_timeline.csv) file, as I am currently using CSV too

**Comment by sanyam-git** [comment]
@lucasrodes, I am really sorry for the late reply, I had my email notifications somehow turned off and missed it. It seems that this issue is resolved.
- You are totally correct, the `total` refers to the cumulative and `count` refers to the daily number of doses administered. 
- India will start administering the second dose from 13 Feb, till then `1 dose = 1 vaccination` holds good. After that I will have to make changes based on how government will be providing the data. (I will inform you about any major changes)
