### ISSUE TITLE
Adding different fields for doses and vaccinated

### ISSUE THREAD

**Issue by sanyam-git** [india-covid19vaccine/india-covid19vaccine.github.io#3]
India has started giving the second dose (the full vaccination is called when two doses are given) from 13th Feb. some additions and altering is needed to be done to accommodate these changes.

@lucasrodes, your input will be helpful
You are currently using the [state_timeline.csv](https://india-covid19vaccine.github.io/csv/state_timeline.csv) in your project.
I have to make some changes and the new fields as described below:

I think using the [state_timeline.json](https://india-covid19vaccine.github.io/api/state_timeline.json) instead of the CSV file will be a better option.

The current structure of state_timeline.json

```
[
  {
    "state_code": "AN",
    "state": "A & N Islands",
    "data": [
      {
        "date": "11/2/2021",
        "total": 3454,
        "count": 41
      }
    ]
  }
]
```

I am planning to add to change it to:
```
[
  {
    "state_code": "AN",
    "state": "A & N Islands",
    "data": [
      {
        "date": "11/2/2021",
        "total_doses":3490,
        "total_vaccinated":3454,
        "total_fully_vaccinated:36
      }
    ]
  }
]
```
where
- `total_doses` is equivalent to total_vaccinations
- `total_vaccinated` is equivalent to people_vaccinated
- `total_fully_vaccinated` is equivalent to people_fully_vaccinated
(as per your documentation)

I plan to generate the equivalent csv file also (may take 3-4 days), in such a manner:

| state_code | date      | total_doses | total_vaccinated | total_fully_vaccinated |
|------------|-----------|-------------|------------------|------------------------|
| AN         | 10/2/2021 | 2343        | 324              | 24                     |
| AN         | 11/2/2021 | 324         | 324              | 12                     |
| AP         | 10/2/2021 | 324         | 34               | 4                      |
| AP         | 11/2/2021 | 32          | 24               | 124                    |

(please don't mind the data, its just some gibberish)

- I think you should use state_timeline.json, thoughts ?
- Any suggestions you have for the changes and new structure ?

**Comment by lucasrodes** [comment]
Hi @sanyam-git ,
Thank you so much for working on this and incorporating the new updates into your data. It is extremely useful for my project.

So far I have been using the [state_timeline.csv](../tree/main/csv/state_timeline.csv) file as I thought it was the only file having all state data in one place (I was not aware of file [state_timeline.json](../tree/main/api/state_timeline.json)) and because I find it easier to read from CSV files (instead of nested JSON files) with pandas. 

I will follow your advice and read from the updated [state_timeline.json](../tree/main/api/state_timeline.json) file from now on.

I think the structure that you propose is perfect and should be easy to integrate. Please ping me once you have updated the data files so I can make the corresponding changes.

Thanks for letting me know 😄 !

**Comment by sanyam-git** [comment]
Completed [here](https://github.com/sociepy/covid19-vaccination-subnational/issues/30).
