### ISSUE TITLE
Values haven't changed

### ISSUE THREAD

**Issue by lucasrodes** [india-covid19vaccine/india-covid19vaccine.github.io#4]
Hi,
I detected that values in your data have not changed since 26th of February (i.e. values for fields `total_doses`, `total_vaccinated` and `total_fully_vaccinated` do not change).

Is this the expected behaviour because - I am speculating here - no new data updates were available on those days?

I have checked on Gov's website and seems that values have slightly changed for 2 March ([ref](https://www.mohfw.gov.in/pdf/CumulativeCOVIDVaccinationCoverageReport2March2021.pdf)). Are these to be added in the next data update?

Anyway, thanks for your help!

**Comment by sanyam-git** [comment]
Hi @lucasrodes ,
- Reason for or no value change on 27th and 28th Feb : no sessions were scheduled because of CoWIN software update ([ref](https://pib.gov.in/PressReleasePage.aspx?PRID=1701013))
- Reasons for no update from 1st March :  state(region) wise data was not made available on the [regular source](https://pib.gov.in/allRel.aspx) from 1st March and I was kind of busy this week, so thought of sorting the issue this weekend. I have found some other sources and will update all the pending data by this Saturday. 

Hope that works :)

**Comment by lucasrodes** [comment]
Awesome @sanyam-git, thanks for your answer. Let me know if you need any help!

**Comment by sanyam-git** [comment]
@lucasrodes updated ! Thanks for the ping.
Closing the issue after resolve.
